what works

diff --git a/netstart b/netstart
--- a/netstart
+++ b/netstart
@@ -1,6 +1,6 @@
 #!/bin/sh -
 #
-#	$OpenBSD: netstart,v 1.119 2008/04/17 19:03:25 deraadt Exp $
+#	$OpenBSD: netstart,v 1.114 2006/06/29 17:23:28 todd Exp $
 
 # Strip comments (and leading/trailing whitespace if IFS is set)
 # from a file and spew to stdout
@@ -26,6 +26,57 @@ isalphanumeric() {
 	return 0
 }
 
+# Spew to stdout $etc/$1 if it exists, otherwise /etc/$1
+nets_file() {
+	local n
+	[ -f $etc/$1 ] && n=$etc || n=/etc
+	echo $n/$1
+}
+
+# tear down an if all ways we know how
+#  how to notify dhclient, rtsold, rtadvd, dhcpd??
+#  in teardown, build a list of if's to teardown, and their inet/inet6 addrs
+#  when setting if addrs, save this info
+#  afterwords, go through each if, compare addrs, if teardown lists something
+#   that setting if addrs did not, then remove it
+#  XXX this is broken currently for diskless setups especially
+teardown() {
+	if="$1"
+
+	# down the if, error on down means $if is perhaps nonexistent
+	ifconfig $if down || return
+	# delete trunkports
+	ifconfig $if | while read line; do
+		set -- $line
+		case "$1" in
+		trunkport) ifconfig $if -trunkport $2 > /dev/null 2>&1 ;;
+		esac
+	done
+	# If we can, destroy the if
+	ifconfig $if destroy > /dev/null 2>&1 && return
+	# remove all v4 addresses, error means no more to remove
+	while ifconfig $if -alias> /dev/null 2>&1; do :; done
+	# remove all v6 addresses
+	ifconfig $if | while read line; do
+		set -- $line
+		case "$1" in
+		inet6) ifconfig $if inet6 delete $2 >/dev/null 2>&1 ;;
+		esac
+	done
+	# remove groups
+	# -link* stuff, also consider for nfsroot and link specific if's
+
+	# reset to default settings
+	for op in -txpower -bssid -chan "media autoselect" 'nwid ""' -nwkey \
+		'mtu 1500' -description
+#-anycast arp -debug -powersafe \
+#		-pppoeac -pppoesvc -syncdev -syncpeer -tentative -txpower \
+#		-vlandev
+	do
+		ifconfig $if $op > /dev/null 2>&1
+	done
+}
+
 # Start the $1 interface
 ifstart() {
 	if=$1
@@ -34,14 +85,27 @@ ifstart() {
 	if ! isalphanumeric "$if"; then
 		return
 	fi
+	# Do not process the same if twice
+	ifseen $if || return
 
-	file=/etc/hostname.$if
-	if [ "$(stat -f "%SLp" $file)" != "---" ]; then
+	file=$(nets_file hostname.$if)
+	if ! [ -f $file ]; then
+		echo "netstart: $file: No such file or directory"
+		return
+	fi
+	if [ "$(stat -f "%SLp %u %g" $file)" != "--- 0 0" ]; then
 		echo "WARNING: $file is insecure, fixing permissions"
 		chmod o-rwx $file
+		chown root.wheel $file
 	fi
+
 	ifconfig $if > /dev/null 2>&1
-	if [ "$?" != "0" ]; then
+	ret=$?
+	if [ $ret == "0" ]; then
+		# Clean the if of any existing addresses
+		teardown $if
+	fi
+	if [ "$ret" != "0" ]; then
 		# Try to create interface if it does not exist
 		ifconfig $if create > /dev/null 2>&1
 		if [ "$?" != "0" ]; then
@@ -49,7 +113,7 @@ ifstart() {
 		fi
 	fi
 
-	# Now parse the hostname.* file
+	# Now parse the $file file
 	while :; do
 		if [ "$cmd2" ]; then
 			# We are carrying over from the 'read dt dtaddr'
@@ -75,7 +139,7 @@ ifstart() {
 			cmd="${af#*!} ${name} ${mask} ${bcaddr} ${ext1} ${ext2}"
 			;;
 		"bridge")
-			cmd="echo /etc/hostname.$if: bridges now supported via bridgename.* files"
+			cmd="echo $file: bridges now supported via bridgename.* files"
 			;;
 		"dhcp")
 			[ "$name" = "NONE" ] && name=
@@ -117,7 +181,7 @@ ifstart() {
 				;;
 			esac
 			if [ ! -n "$name" ]; then
-				echo "/etc/hostname.$if: invalid network configuration file"
+				echo "$file: invalid network configuration file"
 				return
 			fi
 			case $af in
@@ -139,7 +203,7 @@ ifstart() {
 			;;
 		esac
 		eval "$cmd"
-	done < /etc/hostname.$if
+	done < $file
 }
 
 # Start multiple:
@@ -147,13 +211,15 @@ ifstart() {
 #   don't start "$2" interfaces
 ifmstart() {
 	for sif in ${1:-ALL}; do
-		for hn in /etc/hostname.*; do
+		# process both $etc and /etc, duplicates get ignored in ifstart
+		for hn in $etc/hostname.* /etc/hostname.*; do
 			# Strip off /etc/hostname. prefix
 			if=${hn#/etc/hostname.}
+			if=${if#${etc}/hostname.}
 			test "$if" = "*" && continue
-
+	
 			# Skip unwanted ifs
-			s=""
+			s=""	
 			for xf in $2; do
 				test "$xf" = "${if%%[0-9]*}" && s="1" && break
 			done
@@ -167,23 +233,37 @@ ifmstart() {
 	done
 }
 
+# Store if's seen in an array, _ifseen[], and return 1
+# when we are passed "$1" with an if we have already seen
+ifseen() {
+	if=$1
+	for tif in ${_ifseen[@]}
+	do
+		[ "$if" = "$tif" ] && return 1
+	done
+	_ifseen[${#_ifseen[*]}]=$if
+}
+
 # Start the $1 bridge
 bridgestart() {
+	if=$1
 	# Interface names must be alphanumeric only.  We check to avoid
 	# configuring backup or temp files, and to catch the "*" case.
-	if ! isalphanumeric "$1"; then
+	if ! isalphanumeric "$if"; then
 		return
 	fi
-	brconfig $1 > /dev/null 2>&1
+	# Do not process the same if twice
+	ifseen $if || return
+	brconfig $if > /dev/null 2>&1
 	if [ "$?" != "0" ]; then
 		# Try to create interface if it does not exist
-		ifconfig $1 create > /dev/null 2>&1
+		ifconfig $if create > /dev/null 2>&1
 		if [ "$?" != "0" ]; then
 			return
 		fi
 	fi
-
-	# Now parse the bridgename.* file
+	br_file=$(nets_file bridgename.$if)
+	# Now parse the $br_file file
 	# All lines are run as brconfig(8) commands.
 	while read line ; do
 		line=${line%%#*}		# strip comments
@@ -193,45 +273,74 @@ bridgestart() {
 			cmd="${line#*!}"
 			;;
 		*)
-			cmd="brconfig $1 $line"
+			cmd="brconfig $if $line"
 			;;
 		esac
 		eval "$cmd"
-	done < /etc/bridgename.$1
+	done < $br_file
 }
 
 # Re-read /etc/rc.conf
 . /etc/rc.conf
 
-# If we were invoked with a list of interface names, just reconfigure these
-# interfaces (or bridges) and return.
 if [ $1x = autobootx ]; then
 	shift
 fi
-if [ $# -gt 0 ]; then
-	while [ $# -gt 0 ]; do
-		if [ -f /etc/bridgename.$1 ]; then
-			bridgestart $1
-		else
-			ifstart $1
-		fi
-		shift
-	done
-	return
+# if default exists (we have run 'netstart <location>' before), use it
+if [ -d /etc/nets/default -a ! "$1" ]; then
+	set -- "default"
+fi
+# If we are given a 'location' subdir as an argument, over-ride default
+# network configuration file location via $etc
+if [ "$1" -a -d /etc/nets/$1 ]; then
+	etc=/etc/nets/$1
+	# `save' the setup for next reboot
+	if ! [ "$1" = "default" ]; then
+		rm -f /etc/nets/default
+		ln -s $1 /etc/nets/default
+	fi
+	[ -f $etc/rc.conf ] && . $etc/rc.conf
+	shift
+else
+	# setting this permts simpler logic later on
+	etc=/etc
+	# If we are invoked with no args, next reboot should use /etc/ too
+	[ -d /etc/nets/default ] && rm /etc/nets/default
+	# If we were invoked with a list of interface names, just reconfigure
+	# these interfaces (or bridges) and return.
+	if [ $# -gt 0 ]; then
+		while [ $# -gt 0 ]; do
+			if [ -f $(nets_file bridgename.$1) ]; then
+				bridgestart $1
+			else
+				ifstart $1
+			fi
+			shift
+		done
+		return
+	fi
 fi
 
 # Otherwise, process with the complete network initialization.
 
+# Flush routes but do not flush IPSec flows,
+# incase we are processing a 'location', including
+# `back to default' aka 'sh /etc/netstart'
+route -qn flush -inet
+route -qn flush -inet6
+
 # /etc/myname contains my symbolic name
-if [ -f /etc/myname ]; then
-	hostname=`stripcom /etc/myname`
+myname_file=`nets_file myname`
+if [ -f $myname_file ]; then
+	hostname=`stripcom $myname_file`
 	hostname $hostname
 else
 	hostname=`hostname`
 fi
 
-if [ -f /etc/defaultdomain ]; then
-	domainname `stripcom /etc/defaultdomain`
+domain_file=`nets_file defaultdomain`
+if [ -f $domain_file ]; then
+	domainname `stripcom $domain_file`
 fi
 
 # Set the address for the loopback interface.  Bringing the
@@ -266,10 +375,6 @@ if ifconfig lo0 inet6 >/dev/null 2>&1; then
 	route -qn add -inet6 2002:0000:: -prefixlen 24 ::1 -reject > /dev/null
 	route -qn add -inet6 2002:ff00:: -prefixlen 24 ::1 -reject > /dev/null
 
-	# Disallow packets without scope identifier.
-	route -qn add -inet6 ff01:: -prefixlen 16 ::1 -reject > /dev/null
-	route -qn add -inet6 ff02:: -prefixlen 16 ::1 -reject > /dev/null
-
 	# Completely disallow packets to IPv4 compatible prefix.
 	# This may conflict with RFC1933 under following circumstances:
 	# (1) An IPv6-only KAME node tries to originate packets to IPv4
@@ -296,11 +401,6 @@ fi
 # Refer to hostname.if(5) and bridgename.if(5)
 ifmstart "" "trunk vlan carp gif gre pfsync pppoe"
 
-# The trunk interfaces need to come up first in this list.
-# The vlan interfaces need to come up after trunk.
-# Configure all the carp interfaces which we know about before default route.
-ifmstart "trunk vlan carp"
-
 if [ "$ip6kernel" = "YES" -a "x$rtsolif" != "x" ]; then
 	fw=`sysctl -n net.inet6.ip6.forwarding`
 	ra=`sysctl -n net.inet6.ip6.accept_rtadv`
@@ -311,15 +411,28 @@ if [ "$ip6kernel" = "YES" -a "x$rtsolif" != "x" ]; then
 		echo "WARNING: inconsistent config - check /etc/sysctl.conf for IPv6 autoconf"
 	fi
 fi
+if [ "$ip6kernel" = "YES" ]; then
+	# this is to make sure DAD is completed before going further.
+	sleep `sysctl -n net.inet6.ip6.dad_count`
+fi
 
-# /etc/mygate, if it exists, contains the name of my gateway host
-# that name must be in /etc/hosts.
-[[ -z $dhcpif ]] && stripcom /etc/mygate | while read gw; do
+# The trunk interfaces need to come up first in this list.
+# The vlan interfaces need to come up after trunk.
+# The pfsync interfaces need to come up before carp.
+# Configure all the carp interfaces which we know about.
+# They must come up after pfsync but before default route.
+ifmstart "trunk vlan pfsync carp"
+
+gate_file=`nets_file mygate`
+# $gate_file, if it exists, contains the address(es) of the
+# default gateway(s).  Use for IPv4 if no interfaces configured
+# via dhcp.  Use for IPv6 if no interfaces configured via rtsol.
+[[ -z $dhcpif ]] && stripcom $gate_file | while read gw; do
 		[[ $gw == @(*:*) ]] && continue
 		route -qn delete default > /dev/null 2>&1
 		route -qn add -host default $gw && break
 done
-[[ -z $rtsolif ]] && stripcom /etc/mygate | while read gw; do
+[[ -z $rtsolif ]] && stripcom $gate_file | while read gw; do
 		[[ $gw == !(*:*) ]] && continue
 		route -qn delete -inet6 default > /dev/null 2>&1
 		route -qn add -host -inet6 default $gw && break
@@ -333,7 +446,6 @@ done
 # NO			YES			none installed	daemon will run
 # YES/interface		NO			-interface	YES=def. iface
 #	   Any other combination		-reject		config error
-route -qn delete 224.0.0.0/4 > /dev/null 2>&1
 case "$multicast_host:$multicast_router" in
 NO:NO)
 	route -qn add -net 224.0.0.0/4 -interface 127.0.0.1 -reject > /dev/null
@@ -341,7 +453,7 @@ NO:NO)
 NO:YES)
 	;;
 *:NO)
-	maddr=`if [ "$multicast_host" = "YES" ]; then
+	set `if [ $multicast_host = YES ]; then
 		ed -s '!route -qn show -inet' <<EOF
 /^default/p
 EOF
@@ -349,14 +461,8 @@ EOF
 		ed -s "!ifconfig $multicast_host" <<EOF
 /^	inet /p
 EOF
-	fi 2> /dev/null`
-	if [ "X${maddr}" != "X" ]; then
-		set $maddr
-		route -qn add -net 224.0.0.0/4 -interface $2 > /dev/null
-	else
-		route -qn add -net 224.0.0.0/4 -interface \
-			127.0.0.1 -reject > /dev/null
-	fi
+	fi`
+	route -qn add -net 224.0.0.0/4 -interface $2 > /dev/null
 	;;
 *:*)
 	echo 'config error, multicasting disabled until rc.conf is fixed'
@@ -373,15 +479,12 @@ ifmstart "pppoe gif gre"
 route -qn add -net 127 127.0.0.1 -reject > /dev/null
 
 # Configure all the bridges.
-for bn in /etc/bridgename.*; do
+for bn in $etc/bridgename.* /etc/bridgename.*; do
 	# Strip off /etc/bridgename. prefix
-	if=${bn#/etc/bridgename.}
-	test "$if" = "*" && continue
+	bn=${bn#/etc/bridgename.}
+	bn=${bn#${etc}/bridgename.}
+	test "$bn" = "*" && continue
 
 	bridgestart $if
 done
 
-if [ "$ip6kernel" = "YES" ]; then
-	# this is to make sure DAD is completed before going further.
-	sleep `sysctl -n net.inet6.ip6.dad_count`
-fi
